### PR TITLE
Prettier configuration

### LINKED ISSUE #21: Prettier configuration
Add `.prettierrc` to the project with the Airbnb config.

### PR DESCRIPTION
**Pull request by Manas-Kenge**
Fixes #21

### CODE REVIEW

**Comment by khattakdev** [comment]
@Manas-Kenge Remove the `Contributing.md` file from PR and we are good to go.

**Comment by khattakdev** [comment]
@Manas-Kenge resolve the conflicts please.

**Comment by Manas-Kenge** [comment]
@khattakdev I am new to this. Can you please tell me how to resolve the conflict?

**Comment by khattakdev** [comment]
> @khattakdev I am new to this. Can you please tell me how to resolve the conflict?

- Pull the main branch using `git pull origin main` (change `origin` to whatever name you're using, you can see that using `git remove -v`)
- Update the README.md by keeping it same as of the `main` branch.
- Push the changes.

**Pull request closed without merging**
