### PR TITLE
🚀 Added image opening functionality

### PR DESCRIPTION
**Pull request by hammadsaedi**
Modified the extension code to open images with a clickable link. Now, when you save an image, you can click on the "Open Image" link in the information message to open the image using the default system image viewer.

### CODE REVIEW

**Comment by hammadsaedi** [comment]
@khattakdev can you review this?

**Comment by hammadsaedi** [comment]
there was a merge conflict due to a recent update via https://github.com/khattakdev/capture/issues/15, I have resolved this.

**Comment by khattakdev** [comment]
@hammadsaedi please resolve the conflicts - so I can review this.

**Comment by hammadsaedi** [comment]
@khattakdev resolved :)

**Comment by khattakdev** [comment]
@hammadsaedi some more conflicts :)

**Comment by hammadsaedi** [comment]
@khattakdev done: third time :(
pls, merge it first 🗿

**Pull request merged**
